name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install packages
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Export static files
        run: npm run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Add CNAME
        run: echo "condition.js.org" > demo/out/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: demo/out
